name: Test Action

on: push

jobs:
  remote:
    runs-on: self-hosted
    env:
      SSH_PRIVATE_KEY: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAYEAttelS6S/d6nsd3Na3EdNcDxaoDNOOZYBKCTqfSMEz4oIB7+IXH3g
        s410myai2SJZrkJggkw663qOpfeBLdxAAGiqZkZRRP+ZSK4Dh0Ft7HheWY7lW+NYg3KOB8
        o+tE8TE8gY6Yw+jlRLyWYEuoTd31Z7c81itO6CwiHP5Np8fRwxfVhvRUS90e/SwFIrBurI
        OngDWO52GAZcajYhyAJcMJXhc7Fef8OVua7KgE2FXmGZPLXfTwoyS1so+WfHZJoQZ2NeO0
        AiPukaRuQkP6GYZtV4zZdqk/EJr2n/RwQyFGqGHdzs7rAgEAOEgrZqmPpAc0r8b6Z7hbPk
        mGYgVVaAUOrGDgoKuKS/BQYFJWu3GZHrMlsk2FBL+xuGwLQf8HLI+XvH6LXqiedtdM7MEZ
        mFgG7b7aubN79IL3RyCKw9Ah2rE8WOjEgsLIKBfxPnhAyRh2Ij5KU+M3MfL3KNp0RenLL8
        fvPlfyeLfLKSKGjHoRpIirXenE256CKfFtsH318xAAAFmLYtVkO2LVZDAAAAB3NzaC1yc2
        EAAAGBALbXpUukv3ep7HdzWtxHTXA8WqAzTjmWASgk6n0jBM+KCAe/iFx94LONdJsmotki
        Wa5CYIJMOut6jqX3gS3cQABoqmZGUUT/mUiuA4dBbex4XlmO5VvjWINyjgfKPrRPExPIGO
        mMPo5US8lmBLqE3d9We3PNYrTugsIhz+TafH0cMX1Yb0VEvdHv0sBSKwbqyDp4A1judhgG
        XGo2IcgCXDCV4XOxXn/DlbmuyoBNhV5hmTy1308KMktbKPlnx2SaEGdjXjtAIj7pGkbkJD
        +hmGbVeM2XapPxCa9p/0cEMhRqhh3c7O6wIBADhIK2apj6QHNK/G+me4Wz5JhmIFVWgFDq
        xg4KCrikvwUGBSVrtxmR6zJbJNhQS/sbhsC0H/ByyPl7x+i16onnbXTOzBGZhYBu2+2rmz
        e/SC90cgisPQIdqxPFjoxILCyCgX8T54QMkYdiI+SlPjNzHy9yjadEXpyy/H7z5X8ni3yy
        kihox6EaSIq13pxNueginxbbB99fMQAAAAMBAAEAAAGAU41fn519UTV5NWylTJvYqz0pPK
        O1T2NYy/tynBRwklZFLSU9Lubm06YEbxHMwOSNjrAOYfxrwEeVAAqGIWrQZF9v3qSrZphW
        d3vtaNVhYfnvQ4WlEcRmIksq1Cx7UvH/ib6ag77upyOmLjZMWt90dCaU62ojfQKxBf1lfv
        LIiHNluh27Wy/6fgDVkcT6nIKVVQKapPzzQi9F89MgxMEvV5RmHfQjdsbtmJhjORYzp9l5
        qOCDVx8VtJHHu5DM8Q/lQTAkRF9OArSAVuk3qmjQ4liENtC7LNl4wZXNFhI0+fDUVChULv
        V6IbB25pf4AV/TCaGrSohMprVg4C6FnBJgs5aXdtiDgwnRmeOYu9XARvuOq8HLkIH6KuOK
        jNBYa60lDEoL/UTpKpeKOkRyt+PfbkjSJ8VWR73FBxOLQQGD0B0zzxNN2IdxLxVdSIPJrK
        KlgrI+8m7MlsNhbWraOrWYtgEbfpVle1+JWqI7Rk2Z6S9/V/VGe9uzk/8nUJJCoNpxAAAA
        wQCE+rfYmeVi5KHzyedleTOeguZu+pUHSwdlPqW/cxcQlVk3/rZK2U8+ZXfHOxqvp+h400
        hrPm9EMhPqOfwPZa79KJNrWYISWImBi471Evu4+nllLewacJmmqncMub552EzMxtWWZR5H
        JkUdiu/RKXJ4xOUE7/Zx7CLZGf7wlBzFMCnJq1dstnt1Qg/on8vkeo953wqzYgEocIHq2T
        2JHUrjYzccKprMM6ZyJFApSHekimFDXAG3Dz+qSK3kVkzBxOEAAADBAOHIPf/bELd5khWJ
        wrdoIxYDrMe9jUT/Ua/yW1NlEu0QnjaBFF5RRpTxnED6L0l3OpZ5zFpjz99pCargmEpKL7
        qXTK7x2V7afpD/d1p7rcIb/8nyEMWFBBWV9ASLvJwmqNTCKU/h/c777TT5EjF4Vrz0K4Yo
        G6RirVn1WEGRa3B9CDgj/AccVDJfhT6aK4779vOkC6Wio5bhoZEQnvrQht2UAEprCx2t9k
        ufjGWeukrJB6V2jv9kVZN/WsvtK0l+TwAAAMEAz1Ayjgq+1YtWuJsNJeHlpUNlp+p3Dxnh
        nk3nEqPqs3UATw8u6AaxEnyeCF6olCNHtH9+aqSSJn9PaJ7AEApTNAdEU5JggZQwE9TiQN
        jAGEYsLKwIh+P6rqmIEFlxnyGvtLfFTxETEHa56rTki4PViWJFlOQ+8UESvX0HeuIEiT3a
        uezBBgg8CYkmU66/izxrnoPrRu2Mt06kfSUbUNoeJw0OMXMbIo1FgR9rCOkqYIdo+VAlpi
        AAl+fLbJhr02p/AAAAH2FyaWthdGxhc3Jpbml2YXNhcmVkZHk0MjE4QHRlc3QBAgM=
        -----END OPENSSH PRIVATE KEY-----
      SSH_PUBLIC_KEY: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC216VLpL93qex3c1rcR01wPFqgM045lgEoJOp9IwTPiggHv4hcfeCzjXSbJqLZIlmuQmCCTDrreo6l94Et3EAAaKpmRlFE/5lIrgOHQW3seF5ZjuVb41iDco4Hyj60TxMTyBjpjD6OVEvJZgS6hN3fVntzzWK07oLCIc/k2nx9HDF9WG9FRL3R79LAUisG6sg6eANY7nYYBlxqNiHIAlwwleFzsV5/w5W5rsqATYVeYZk8td9PCjJLWyj5Z8dkmhBnY147QCI+6RpG5CQ/oZhm1XjNl2qT8Qmvaf9HBDIUaoYd3OzusCAQA4SCtmqY+kBzSvxvpnuFs+SYZiBVVoBQ6sYOCgq4pL8FBgUla7cZkesyWyTYUEv7G4bAtB/wcsj5e8foteqJ5210zswRmYWAbtvtq5s3v0gvdHIIrD0CHasTxY6MSCwsgoF/E+eEDJGHYiPkpT4zcx8vco2nRF6csvx+8+V/J4t8spIoaMehGkiKtd6cTbnoIp8W2wffXzE=
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup remote
        run: |
          echo "$SSH_PUBLIC_KEY" | sudo tee /etc/ssh/authorized_keys
          sudo tee /etc/ssh/sshd_config <<EOF
            PasswordAuthentication no
            PubkeyAuthentication yes
            AuthorizedKeysFile /etc/ssh/authorized_keys
            PermitRootLogin no
            Subsystem sftp /usr/lib/openssh/sftp-server
          EOF
          sudo systemctl restart sshd
          echo 'SSH_KNOWN_HOSTS<<EOF' >> $GITHUB_ENV
          echo $(ssh-keyscan localhost) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: With everything
        uses: ./
        with:
          playbook: playbook.yml
          key: ${{env.SSH_PRIVATE_KEY}}
          known_hosts: ${{env.SSH_KNOWN_HOSTS}}
          directory: test
          vault_password: test
          requirements: requirements.yml
          inventory: |
            [all]
            localhost
          options: |
            -e docker_image=docker_url
            -e docker_username=user
            -e docker_password=pass
            -e db_name=db_name
            -e db_user=db_user
            -e db_pass=db_pass
  local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: With requirements
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          requirements: requirements.yml
          options: --inventory hosts
      - name: With requirements bundle
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          requirements: requirements-bundle.yml
          options: --inventory hosts
      - name: With vault password
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          vault_password: test
          options: --inventory hosts
      - name: With sudo
        uses: ./
        with:
          playbook: playbook.yml
          directory: test
          sudo: true
          options: --inventory hosts
